name: Containerize the application and push to acr

on:
  push:
    branches: [develop]

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push to docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: noteopx/api-gateway:latest, noteopx/api-gateway:${{ env.IMAGE_TAG }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Start updating manifest
        run: |
          echo $PWD
          bash ./build.sh
        env:
          GH_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          GH_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy service
    needs: build-container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          ref: refs/heads/develop
          repository: cocoon-letters-limited/notes-manifest
          token: ${{ secrets.GIT_TOKEN }} # `GH_PAT` is a secret that contains your PAT
          path: .
      - name: Setting context
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          resource-group: ${{ secrets.RESOURCE_GROUP }}
      - uses: Azure/k8s-deploy@v4
        with:
          manifests: |
            api-gateway.yml
