name: Containerize the application and push to acr

on:
  push:
    branches: [develop]

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push to docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: noteopx/api-gateway:latest, noteopx/api-gateway:${{ github.run_number }}
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
#         working-directory: .
#     steps:
#       - uses: actions/checkout@v2
#       - uses: azure/docker-login@v1
#         with:
#           login-server: noteopxacr.azurecr.io
#           username: ${{ secrets.REGISTRY_USERNAME }}
#           password: ${{ secrets.REGISTRY_PASSWORD }}
#       - run: |
#           docker build -t noteopxacr.azurecr.io/backend/api-gateway:${{ github.sha }} .
#           docker push noteopxacr.azurecr.io/backend/api-gateway:${{ github.sha }}
